version: '3.2'
services:
  lua:
    build: .
    environment:
      - LUA_PATH="/okta-auth/?.lua;/okta-auth/?/init.lua;;"
      - KONG_PATH="/kong"
      - KONG_CUSTOM_PLUGINS="kong-plugin-okta-auth"
    volumes:
      - .:/okta-auth

  kong-database:
    image: postgres:9.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong

  apigw:
    build:
      context: .
      dockerfile: apigw.dockerfile
    depends_on:
      - kong-database
    links:
      - kong-database
    environment:
      - KONG_PG_HOST=kong-database
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_CUSTOM_PLUGINS=okta-auth,zipkin
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - OKTA_BASE_URL
      - OKTA_CLIENT_ID
      - OKTA_CLIENT_SECRET
      - OKTA_AUTH_SERVER_ID
      - OKTA_UNKOWN_AUTH_SERVER_ID
      - OKTA_BASIC_TOKEN
      - EXPIRED_TOKEN
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444
